FROM debian:stable-slim

RUN apt update \
    && apt install -y openssh-server openssh-client \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

RUN echo 'root:password' | chpasswd
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config

EXPOSE 2222
CMD ["/usr/sbin/sshd", "-D", "-p", "2222"]
